

services:
  qdrant:
      image: qdrant/qdrant:latest
      ports:
        - "6333:6333"
      volumes:
        - ./qdrant_data:/qdrant/storage

  postgres:
      image: postgres:latest
      ports:
        - "5432:5432"
      env_file: .env
      volumes:
        - ./postgres_data:/var/lib/postgresql/data